# Generated by Django 4.2.14 on 2024-10-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco', '0002_alter_plant_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='age',
            field=models.IntegerField(default=1),
        ),
    ]
